### ISSUE TITLE
Adapt the theme to the upcoming Discourse changes

### ISSUE THREAD

**Issue by bfabio** [italia/forum.italia.it#9]
Check the theme and adapt it to the upcoming changes (and then sync it to this repo):

![image](https://github.com/user-attachments/assets/eec23280-8950-4f00-bc3a-7f4ea86a287c)

ref: https://meta.discourse.org/t/upcoming-header-changes-preparing-themes-and-plugins/296544

**Comment by tensor5** [comment]
Fixed by 0f1f7b8e8467ae232e86e3be03f52e524251297e and 201f64df8f0262f42b26dbdb4f94170ffe1f711b.
